### ISSUE TITLE
LDAP server not found

### ISSUE THREAD

**Issue by 7MinSec** [AlmondOffSec/PassTheCert#2]
Hello!

Per [this thread](https://github.com/ly4k/Certipy/issues/64) I'm excited to give PassTheCert a try but am having an issue.  When I run this...

`PassTheCert.exe --server FQDN.OF.A.DOMAINCONTROLLER --cert-path domainadmin.pfx --elevate --target "DC=victim,DC=domain" --sid XXX`

I get this:

````
Unhandled Exception: System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable.
   at System.DirectoryServices.Protocols.LdapConnection.Connect()
   at System.DirectoryServices.Protocols.LdapConnection.SendRequestHelper(DirectoryRequest request, Int32& messageID)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at PassTheCert.Program.GetSecurityDescriptor(LdapConnection connection, String target, String filter, String attribute, Boolean flag_control)
   at PassTheCert.Program.AclAttack(LdapConnection connection, String target, String filter, String attribute, AccessControlEntry[] new_aces, String restore_file, Boolean flag_control)
   at PassTheCert.Program.ElevateUserAttack(LdapConnection connection, String target, String sid, String restore_file)
   at PassTheCert.Program.Main(String[] args)
````

Any thoughts?  The `FQDN.OF.A.DOMAINCONTROLLER` is resolvable and online (and a DC :-)

**Comment by 7MinSec** [comment]
Not sure if it matters, but one thing I noticed is if I do `nmap -p389,636 FQDN.OF.A.DOMAINCONTROLLER` it reports as "down" but if I add the no-ping flag of `-Pn` the nmap finishes with the results I expect.

**Comment by the-useless-one** [comment]
Hi!

By default, PassTheCert tries the LDAPS port. Is it reported as open in your `nmap` scan? Either way, you can try using `--start-tls`, which will connect to the LDAP port. Let me know your results.

**Comment by 7MinSec** [comment]
Thank you again @the-useless-one for the super fast help.  The LDAPS did report as open.  

This is a huge environment and I tried all the other DCs just for grins, and the last one worked!  So I didn't end up trying `start-tls` but I'll make note of it.  

I'll check my new (hopefully) super powers and report back on the certipy thread as to how things go...

**Comment by DeserranoJorden** [comment]
Hi,

I'm currently having the same issue.
I started troubleshooting the same way @braimee did here, starting all the way back from the Certipy thread.
Likewise, I also received the `Kerberos SessionError: KDC_ERR_PADATA_TYPE_NOSUPP(KDC has no support for padata type)` error. And I'm currently stuck on the error showed below.

```
Unhandled Exception: System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable.
   at System.DirectoryServices.Protocols.LdapConnection.Connect()
   at System.DirectoryServices.Protocols.LdapConnection.SendRequestHelper(DirectoryRequest request, Int32& messageID)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at PassTheCert.Program.GetSecurityDescriptor(LdapConnection connection, String target, String filter, String attribute, Boolean flag_control) in [PATH]\PassTheCert.cs:line 117
   at PassTheCert.Program.AclAttack(LdapConnection connection, String target, String filter, String attribute, AccessControlEntry[] new_aces, String restore_file, Boolean flag_control) in [PATH]\PassTheCert.cs:line 205
   at PassTheCert.Program.ElevateUserAttack(LdapConnection connection, String target, String sid, String restore_file) in [PATH]\PassTheCert.cs:line 228
   at PassTheCert.Program.Main(String[] args) in [PATH]\PassTheCert.cs:line 491
```

I've tried different DCs, all with port 389 and 636 fully open (as shown in nmap).
The `--start-tls` also just throws a different error for me.

```
Unhandled Exception: System.DirectoryServices.Protocols.TlsOperationException: An unspecified operation error occurred.
   at System.DirectoryServices.Protocols.LdapSessionOptions.StartTransportLayerSecurity(DirectoryControlCollection controls)
   at PassTheCert.Program.Main(String[] args) in [PATH]\PassTheCert.cs:line 479
```

Any thoughts on why this error occurs?

**Comment by the-useless-one** [comment]
Hi @DeserranoJorden,

This is weird. Would you be able to provide a Wireshark capture? One for LDAPS and one for LDAP with StartTLS would be great.

Cheers,

Y
