### ISSUE TITLE
distutils

### ISSUE THREAD

**Issue by sec13b** [AlmondOffSec/PassTheCert#23]
recently i keep getting this error with distutils.

python3-impacket is already the newest version (0.12.0-2).

~~~~~~~~~~~~~~~~~~~
python3 passthecert.py                                                        
Traceback (most recent call last):
  File "/home/kali/Desktop/PassTheCert/Python/passthecert.py", line 38, in <module>
    from impacket import version
  File "/home/kali/.local/lib/python3.12/site-packages/impacket/version.py", line 10, in <module>
    import pkg_resources
  File "/home/kali/.local/lib/python3.12/site-packages/pkg_resources/__init__.py", line 90, in <module>
    import packaging.markers
  File "/home/kali/.local/lib/python3.12/site-packages/packaging/markers.py", line 25, in <module>
    from .specifiers import InvalidSpecifier, Specifier
  File "/home/kali/.local/lib/python3.12/site-packages/packaging/specifiers.py", line 14, in <module>
    from .utils import canonicalize_version
  File "/home/kali/.local/lib/python3.12/site-packages/packaging/utils.py", line 9, in <module>
    from .tags import Tag, parse_tag
  File "/home/kali/.local/lib/python3.12/site-packages/packaging/tags.py", line 7, in <module>
    import distutils.util
ModuleNotFoundError: No module named 'distutils'
~~~~~~~~~~~~~~~~~~~

**Comment by the-useless-one** [comment]
Hi,

This is a problem with your `impacket` installation and not PassTheCert. Given the path it seems you have installed `impacket` through `pip`, along your `python3-impacket` from your Kali installation.

Cheers,

Y

**Comment by sec13b** [comment]
so NO "sudo apt install python3-impacket"
only
sudo git clone https://github.com/fortra/impacket /opt/impacket
cd /opt/impacket/ && sudo python3 ./setup.py install
