### ISSUE TITLE
LDAP server not found 

### ISSUE THREAD

**Issue by DeserranoJorden** [AlmondOffSec/PassTheCert#6]
Hi,

Following up on issue [https://github.com/AlmondOffSec/PassTheCert/issues/2](https://github.com/AlmondOffSec/PassTheCert/issues/2).

I'm currently having the same issue.
I started troubleshooting the same way @braimee did here, starting all the way back from the Certipy thread.
Likewise, I also received the `Kerberos SessionError: KDC_ERR_PADATA_TYPE_NOSUPP(KDC has no support for padata type)` error. And I'm currently stuck on the error shown below.

```
Unhandled Exception: System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable.
   at System.DirectoryServices.Protocols.LdapConnection.Connect()
   at System.DirectoryServices.Protocols.LdapConnection.SendRequestHelper(DirectoryRequest request, Int32& messageID)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at PassTheCert.Program.GetSecurityDescriptor(LdapConnection connection, String target, String filter, String attribute, Boolean flag_control) in [PATH]\PassTheCert.cs:line 117
   at PassTheCert.Program.AclAttack(LdapConnection connection, String target, String filter, String attribute, AccessControlEntry[] new_aces, String restore_file, Boolean flag_control) in [PATH]\PassTheCert.cs:line 205
   at PassTheCert.Program.ElevateUserAttack(LdapConnection connection, String target, String sid, String restore_file) in [PATH]\PassTheCert.cs:line 228
   at PassTheCert.Program.Main(String[] args) in [PATH]\PassTheCert.cs:line 491
```

I've tried different DCs, all with port 389 and 636 fully open (as shown in nmap).
The `--start-tls` also just throws a different error for me.

```
Unhandled Exception: System.DirectoryServices.Protocols.TlsOperationException: An unspecified operation error occurred.
   at System.DirectoryServices.Protocols.LdapSessionOptions.StartTransportLayerSecurity(DirectoryControlCollection controls)
   at PassTheCert.Program.Main(String[] args) in [PATH]\PassTheCert.cs:line 479
```

Any thoughts on why this error occurs?

My command looks like this:

```
.\PassTheCert.exe --cert-path admin.pfx --elevate --target DC=test,DC=local --sid [SID] --server [DC]
```

**Comment by DeserranoJorden** [comment]
hi @the-useless-one,

Following up your reply on #2. 

I'm currently unable to provide you with a wireshark file (as I'm not testing on a test environment).
I did check the wireshark output from both commands tho.

And I think the problem is pretty straightforward....
My DCs only supports unencrypted LDAP traffic to port 389.

**Comment by the-useless-one** [comment]
So there's no StartTLS support? What about LDAPS, you mentioned that the 636 port is reported open in `nmap`?

**Comment by DeserranoJorden** [comment]
Nope, no StartTLS support. 

I tried both ports on the DC itself through ldp.exe. 
But only an insecure LDAP connection to port 389 was working.

**Comment by DeserranoJorden** [comment]
Thanks for the quick responses @the-useless-one.
It was my own mistake and it worked on a different DC.

**Comment by the-useless-one** [comment]
Glad it worked!
